//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        internal static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar menú personalizado .
        /// </summary>
        internal static string ActivarMenuPersonalizado {
            get {
                return ResourceManager.GetString("ActivarMenuPersonalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregado correctamente.
        /// </summary>
        internal static string AgregadoCorrectamente {
            get {
                return ResourceManager.GetString("AgregadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido M..
        /// </summary>
        internal static string ApellidoM {
            get {
                return ResourceManager.GetString("ApellidoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido P..
        /// </summary>
        internal static string ApellidoP {
            get {
                return ResourceManager.GetString("ApellidoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Árbol.
        /// </summary>
        internal static string Arbol {
            get {
                return ResourceManager.GetString("Arbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Árbol del ménu.
        /// </summary>
        internal static string ArbolMenu {
            get {
                return ResourceManager.GetString("ArbolMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar menú.
        /// </summary>
        internal static string AsignarMenu {
            get {
                return ResourceManager.GetString("AsignarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar colonia.
        /// </summary>
        internal static string BuscarColonia {
            get {
                return ResourceManager.GetString("BuscarColonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar empleado.
        /// </summary>
        internal static string BuscarEmpleado {
            get {
                return ResourceManager.GetString("BuscarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar entidad organigrama.
        /// </summary>
        internal static string BuscarEntidadOrganigrama {
            get {
                return ResourceManager.GetString("BuscarEntidadOrganigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar nivel organigrama.
        /// </summary>
        internal static string BuscarNivelOrganigrama {
            get {
                return ResourceManager.GetString("BuscarNivelOrganigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar puesto.
        /// </summary>
        internal static string BuscarPuesto {
            get {
                return ResourceManager.GetString("BuscarPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar rol.
        /// </summary>
        internal static string BuscarRol {
            get {
                return ResourceManager.GetString("BuscarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar sucursal.
        /// </summary>
        internal static string BuscarSucursal {
            get {
                return ResourceManager.GetString("BuscarSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar usuario.
        /// </summary>
        internal static string BuscarUsuario {
            get {
                return ResourceManager.GetString("BuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario.
        /// </summary>
        internal static string Calendario {
            get {
                return ResourceManager.GetString("Calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        internal static string CambiarContrasena {
            get {
                return ResourceManager.GetString("CambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad por página.
        /// </summary>
        internal static string CantidadPagina {
            get {
                return ResourceManager.GetString("CantidadPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cel.
        /// </summary>
        internal static string Cel {
            get {
                return ResourceManager.GetString("Cel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular.
        /// </summary>
        internal static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        internal static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de seguridad.
        /// </summary>
        internal static string CodigoSeguridad {
            get {
                return ResourceManager.GetString("CodigoSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Col.
        /// </summary>
        internal static string Col {
            get {
                return ResourceManager.GetString("Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia.
        /// </summary>
        internal static string Colonia {
            get {
                return ResourceManager.GetString("Colonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña anterior.
        /// </summary>
        internal static string ContrasenaAnterior {
            get {
                return ResourceManager.GetString("ContrasenaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar menú.
        /// </summary>
        internal static string CopiarMenu {
            get {
                return ResourceManager.GetString("CopiarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar menú de.
        /// </summary>
        internal static string CopiarMenuDe {
            get {
                return ResourceManager.GetString("CopiarMenuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisa tu bandeja de entrada, ahi encontraras las instrucciones para restablecer tu contraseña.
        /// </summary>
        internal static string CorreoEnviado {
            get {
                return ResourceManager.GetString("CorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C.P..
        /// </summary>
        internal static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear usuario.
        /// </summary>
        internal static string CrearUsuario {
            get {
                return ResourceManager.GetString("CrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuidado.
        /// </summary>
        internal static string Cuidado {
            get {
                return ResourceManager.GetString("Cuidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cumpleañero del mes.
        /// </summary>
        internal static string CumpleaneroMes {
            get {
                return ResourceManager.GetString("CumpleaneroMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURP.
        /// </summary>
        internal static string Curp {
            get {
                return ResourceManager.GetString("Curp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del encargado.
        /// </summary>
        internal static string DatosEncargado {
            get {
                return ResourceManager.GetString("DatosEncargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la sucursal.
        /// </summary>
        internal static string DatosSucursal {
            get {
                return ResourceManager.GetString("DatosSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de usuario para persona encargada.
        /// </summary>
        internal static string DatosUsuarioEncargado {
            get {
                return ResourceManager.GetString("DatosUsuarioEncargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshabilitado correcto.
        /// </summary>
        internal static string DeshabilitadoCorrecto {
            get {
                return ResourceManager.GetString("DeshabilitadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshabilitar.
        /// </summary>
        internal static string Deshabilitar {
            get {
                return ResourceManager.GetString("Deshabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino.
        /// </summary>
        internal static string Destino {
            get {
                return ResourceManager.GetString("Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        internal static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles empleado.
        /// </summary>
        internal static string DetallesEmpleado {
            get {
                return ResourceManager.GetString("DetallesEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles sucursal.
        /// </summary>
        internal static string DetallesSucursal {
            get {
                return ResourceManager.GetString("DetallesSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles usuario.
        /// </summary>
        internal static string DetallesUsuario {
            get {
                return ResourceManager.GetString("DetallesUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        internal static string Edad {
            get {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado correctamente.
        /// </summary>
        internal static string EliminadoCorrecto {
            get {
                return ResourceManager.GetString("EliminadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        internal static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado encargado.
        /// </summary>
        internal static string EmpleadoEncargado {
            get {
                return ResourceManager.GetString("EmpleadoEncargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encargado.
        /// </summary>
        internal static string Encargado {
            get {
                return ResourceManager.GetString("Encargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encontrados.
        /// </summary>
        internal static string Encontrados {
            get {
                return ResourceManager.GetString("Encontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad.
        /// </summary>
        internal static string Entidad {
            get {
                return ResourceManager.GetString("Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidades organigrama.
        /// </summary>
        internal static string EntidadesOrganigrama {
            get {
                return ResourceManager.GetString("EntidadesOrganigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entre.
        /// </summary>
        internal static string Entre {
            get {
                return ResourceManager.GetString("Entre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entre calle.
        /// </summary>
        internal static string EntreCalles1 {
            get {
                return ResourceManager.GetString("EntreCalles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y calle.
        /// </summary>
        internal static string EntreCalles2 {
            get {
                return ResourceManager.GetString("EntreCalles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurrio un error con la base de datos.
        /// </summary>
        internal static string ErrorBaseDatos {
            get {
                return ResourceManager.GetString("ErrorBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del código postal consta de 5 números.
        /// </summary>
        internal static string ErrorCodigoPostal {
            get {
                return ResourceManager.GetString("ErrorCodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña anterior es incorrecta.
        /// </summary>
        internal static string ErrorContrasenaAnterior {
            get {
                return ResourceManager.GetString("ErrorContrasenaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de destino incorrecto, formato: /Controlador/Accion.
        /// </summary>
        internal static string ErrorDireccionMvc {
            get {
                return ResourceManager.GetString("ErrorDireccionMvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de contraseña incorrecto.
        /// </summary>
        internal static string ErrorFormatoContrasena {
            get {
                return ResourceManager.GetString("ErrorFormatoContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato inválido.
        /// </summary>
        internal static string ErrorFormatoInvalido {
            get {
                return ResourceManager.GetString("ErrorFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con el empleado a guardar.
        /// </summary>
        internal static string ErrorIdEmpleado {
            get {
                return ResourceManager.GetString("ErrorIdEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string ErrorNoCoincidenContrasenas {
            get {
                return ResourceManager.GetString("ErrorNoCoincidenContrasenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se permiten letras.
        /// </summary>
        internal static string ErrorSoloLetras {
            get {
                return ResourceManager.GetString("ErrorSoloLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El télefono consta de 10 digitos, siendo los primeros 3 la LADA.
        /// </summary>
        internal static string ErrorTelefono {
            get {
                return ResourceManager.GetString("ErrorTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario o contraseña incorrecta.
        /// </summary>
        internal static string ErrorUsuarioIncorrecto {
            get {
                return ResourceManager.GetString("ErrorUsuarioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario que esta intentando ingresar se encuentra deshabilitado.
        /// </summary>
        internal static string ErrorUsuarioInhabilitado {
            get {
                return ResourceManager.GetString("ErrorUsuarioInhabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló al agregar.
        /// </summary>
        internal static string FalloAgregar {
            get {
                return ResourceManager.GetString("FalloAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló al deshabilitar el/la {0}.
        /// </summary>
        internal static string FalloDeshabilitar {
            get {
                return ResourceManager.GetString("FalloDeshabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al eliminar el/la {0}.
        /// </summary>
        internal static string FalloEliminado {
            get {
                return ResourceManager.GetString("FalloEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un fallo al intentar enviar un mensaje al correo electrónico proporcionado.
        /// </summary>
        internal static string FalloEnviarCorreo {
            get {
                return ResourceManager.GetString("FalloEnviarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el/la {0}.
        /// </summary>
        internal static string FalloGuardado {
            get {
                return ResourceManager.GetString("FalloGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló al habilitar el/la {0}.
        /// </summary>
        internal static string FalloHabilitar {
            get {
                return ResourceManager.GetString("FalloHabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló al quitar.
        /// </summary>
        internal static string FalloQuitar {
            get {
                return ResourceManager.GetString("FalloQuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creación.
        /// </summary>
        internal static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Ingr..
        /// </summary>
        internal static string FechaIngreso {
            get {
                return ResourceManager.GetString("FechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Nac..
        /// </summary>
        internal static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto.
        /// </summary>
        internal static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género.
        /// </summary>
        internal static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar rol.
        /// </summary>
        internal static string GestionarRol {
            get {
                return ResourceManager.GetString("GestionarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado correctamente.
        /// </summary>
        internal static string GuardadoCorrecto {
            get {
                return ResourceManager.GetString("GuardadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar colonia.
        /// </summary>
        internal static string GuardarColonia {
            get {
                return ResourceManager.GetString("GuardarColonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar empleado.
        /// </summary>
        internal static string GuardarEmpleado {
            get {
                return ResourceManager.GetString("GuardarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar entidad organigrama.
        /// </summary>
        internal static string GuardarEntidadOrganigrama {
            get {
                return ResourceManager.GetString("GuardarEntidadOrganigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Menú.
        /// </summary>
        internal static string GuardarMenu {
            get {
                return ResourceManager.GetString("GuardarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar nivel organigrama.
        /// </summary>
        internal static string GuardarNivelOrganigrama {
            get {
                return ResourceManager.GetString("GuardarNivelOrganigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar puesto.
        /// </summary>
        internal static string GuardarPuesto {
            get {
                return ResourceManager.GetString("GuardarPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar rol.
        /// </summary>
        internal static string GuardarRol {
            get {
                return ResourceManager.GetString("GuardarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar sucursal.
        /// </summary>
        internal static string GuardarSucursal {
            get {
                return ResourceManager.GetString("GuardarSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GuardarUsuario.
        /// </summary>
        internal static string GuardarUsuario {
            get {
                return ResourceManager.GetString("GuardarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado correcto.
        /// </summary>
        internal static string HabilitadoCorrecto {
            get {
                return ResourceManager.GetString("HabilitadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitados.
        /// </summary>
        internal static string Habilitados {
            get {
                return ResourceManager.GetString("Habilitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitar.
        /// </summary>
        internal static string Habilitar {
            get {
                return ResourceManager.GetString("Habilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icono css.
        /// </summary>
        internal static string IconoCss {
            get {
                return ResourceManager.GetString("IconoCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INIFE.
        /// </summary>
        internal static string Inife {
            get {
                return ResourceManager.GetString("Inife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        internal static string Latitud {
            get {
                return ResourceManager.GetString("Latitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        internal static string Longitud {
            get {
                return ResourceManager.GetString("Longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar perfil.
        /// </summary>
        internal static string ModificarPerfil {
            get {
                return ResourceManager.GetString("ModificarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        internal static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel organigrama.
        /// </summary>
        internal static string NivelesOrganigrama {
            get {
                return ResourceManager.GetString("NivelesOrganigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel organigrama.
        /// </summary>
        internal static string NivelOrganigrama {
            get {
                return ResourceManager.GetString("NivelOrganigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no existe en nuestra base de datos.
        /// </summary>
        internal static string NoExisteCorreoElectronico {
            get {
                return ResourceManager.GetString("NoExisteCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        internal static string NuevaContrasena {
            get {
                return ResourceManager.GetString("NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        internal static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMSS.
        /// </summary>
        internal static string NumeroImss {
            get {
                return ResourceManager.GetString("NumeroImss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        internal static string OlvidasteContraseña {
            get {
                return ResourceManager.GetString("OlvidasteContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción.
        /// </summary>
        internal static string Opcion {
            get {
                return ResourceManager.GetString("Opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        internal static string Otro {
            get {
                return ResourceManager.GetString("Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de inicio.
        /// </summary>
        internal static string PaginaInicio {
            get {
                return ResourceManager.GetString("PaginaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil del usuario.
        /// </summary>
        internal static string PerfilUsuario {
            get {
                return ResourceManager.GetString("PerfilUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea deshabilitar el/la {0}?.
        /// </summary>
        internal static string PreguntaDeshabilitar {
            get {
                return ResourceManager.GetString("PreguntaDeshabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el/la {0}?.
        /// </summary>
        internal static string PreguntaEliminar {
            get {
                return ResourceManager.GetString("PreguntaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea habilitar el/la {0}?.
        /// </summary>
        internal static string PreguntaHabilitar {
            get {
                return ResourceManager.GetString("PreguntaHabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        internal static string Puesto {
            get {
                return ResourceManager.GetString("Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        internal static string Quitar {
            get {
                return ResourceManager.GetString("Quitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raiz.
        /// </summary>
        internal static string Raiz {
            get {
                return ResourceManager.GetString("Raiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar.
        /// </summary>
        internal static string Recuperar {
            get {
                return ResourceManager.GetString("Recuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro con el mismo valor.
        /// </summary>
        internal static string RegistroExistente {
            get {
                return ResourceManager.GetString("RegistroExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        internal static string Regresar {
            get {
                return ResourceManager.GetString("Regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removido correctamente.
        /// </summary>
        internal static string RemovidoCorrectamente {
            get {
                return ResourceManager.GetString("RemovidoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir contraseña.
        /// </summary>
        internal static string RepetirContrasena {
            get {
                return ResourceManager.GetString("RepetirContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        internal static string Restablecer {
            get {
                return ResourceManager.GetString("Restablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        internal static string RestablecerContrasena {
            get {
                return ResourceManager.GetString("RestablecerContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        internal static string RestablerContrasena {
            get {
                return ResourceManager.GetString("RestablerContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC.
        /// </summary>
        internal static string Rfc {
            get {
                return ResourceManager.GetString("Rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        internal static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione....
        /// </summary>
        internal static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin encargado.
        /// </summary>
        internal static string SinEncargado {
            get {
                return ResourceManager.GetString("SinEncargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin puesto.
        /// </summary>
        internal static string SinPuesto {
            get {
                return ResourceManager.GetString("SinPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin usuario.
        /// </summary>
        internal static string SinUsuario {
            get {
                return ResourceManager.GetString("SinUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar.
        /// </summary>
        internal static string Solicitar {
            get {
                return ResourceManager.GetString("Solicitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar contraseña.
        /// </summary>
        internal static string SolicitarContrasena {
            get {
                return ResourceManager.GetString("SolicitarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursal.
        /// </summary>
        internal static string Sucursal {
            get {
                return ResourceManager.GetString("Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño página.
        /// </summary>
        internal static string TamanoPagina {
            get {
                return ResourceManager.GetString("TamanoPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tel.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Gestión.
        /// </summary>
        internal static string TipoGestion {
            get {
                return ResourceManager.GetString("TipoGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string TipoUsuario {
            get {
                return ResourceManager.GetString("TipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
