//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://gespipci.claro.sonora.gob.mx:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_SIGAF_WS_PRO&receiverParty=&receiverService=&interface=SI_PagoRegistroCivil_out&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FPORTAL%2FWS%2FPagoRegistroCivil")]
        public string Negocio_WsPagoRegistroCivil_Productivo_SI_PagoRegistroCivil_outService {
            get {
                return ((string)(this["Negocio_WsPagoRegistroCivil_Productivo_SI_PagoRegistroCivil_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gespipci.claro.sonora.gob.mx:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=BS_SIGAF_WS_PRO&receiverParty=&receiverService=&interface=SI_Co" +
            "nsultaRo_out&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FTRM%2FPORTAL%2FPagoE" +
            "nLinea")]
        public string Negocio_WsValidarPago_Productivo_SI_ConsultaRo_outService {
            get {
                return ((string)(this["Negocio_WsValidarPago_Productivo_SI_ConsultaRo_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gespipci.claro.sonora.gob.mx:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=BS_SIGAF_WS_PRO&receiverParty=&receiverService=&interface=SI_Pa" +
            "seCaja_out&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FPORTAL%2FWS%2FPaseAcaj" +
            "a")]
        public string Negocio_WsPaseCaja_Productivo_SI_PaseCaja_outService {
            get {
                return ((string)(this["Negocio_WsPaseCaja_Productivo_SI_PaseCaja_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.32.1.103:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "BS_SIGAF_WS&receiverParty=&receiverService=&interface=SI_PaseCaja_out&interfaceN" +
            "amespace=http%3A%2F%2Fgeson.gob.mx%2FPORTAL%2FWS%2FPaseAcaja")]
        public string Negocio_WsPaseCaja_Desarrollo_SI_PaseCaja_outService {
            get {
                return ((string)(this["Negocio_WsPaseCaja_Desarrollo_SI_PaseCaja_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.32.1.103:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "BS_SIGAF_WS&receiverParty=&receiverService=&interface=SI_PagoRegistroCivil_out&i" +
            "nterfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FPORTAL%2FWS%2FPagoRegistroCivil")]
        public string Negocio_WsPagoRegistroCivil_Desarrollo_SI_PagoRegistroCivil_outService {
            get {
                return ((string)(this["Negocio_WsPagoRegistroCivil_Desarrollo_SI_PagoRegistroCivil_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gespiqci.claro.sonora.gob.mx:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=BS_SIGAF_WS_QA&receiverParty=&receiverService=&interface=SI_Con" +
            "sultaRo_out&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FTRM%2FPORTAL%2FPagoEn" +
            "Linea")]
        public string Negocio_WsValidarPago_Calidad_SI_ConsultaRo_outService {
            get {
                return ((string)(this["Negocio_WsValidarPago_Calidad_SI_ConsultaRo_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gespiqci.claro.sonora.gob.mx:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=BS_SIGAF_WS_QA&receiverParty=&receiverService=&interface=SI_Pas" +
            "eCaja_out&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FPORTAL%2FWS%2FPaseAcaja" +
            "")]
        public string Negocio_WsPaseCaja_Calidad_SI_PaseCaja_outService {
            get {
                return ((string)(this["Negocio_WsPaseCaja_Calidad_SI_PaseCaja_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.32.1.123:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "BS_SIGAF_WS_QA&receiverParty=&receiverService=&interface=SI_PagoRegistroCivil_ou" +
            "t&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FPORTAL%2FWS%2FPagoRegistroCivil" +
            "")]
        public string Negocio_WsPagoRegistroCivil_Calidad_SI_PagoRegistroCivil_outService {
            get {
                return ((string)(this["Negocio_WsPagoRegistroCivil_Calidad_SI_PagoRegistroCivil_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sfirmapruebas.sonora.gob.mx/WSPSFIEL/webservice.asmx")]
        public string Negocio_WebReferenceFirma_WebService {
            get {
                return ((string)(this["Negocio_WebReferenceFirma_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gespipci.claro.sonora.gob.mx:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=BS_SIGAF_WS_PRO&receiverParty=&receiverService=&interface=SI_Co" +
            "nsultaRo_out&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FTRM%2FPORTAL%2FPagoE" +
            "nLinea")]
        public string Negocio_mx_gob_sonora_claro_gespipci_SI_ConsultaRo_outService {
            get {
                return ((string)(this["Negocio_mx_gob_sonora_claro_gespipci_SI_ConsultaRo_outService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gespipci.claro.sonora.gob.mx:50000/XISOAPAdapter/MessageServlet?senderPart" +
            "y=&senderService=BS_SIGAF_WS_PRO&receiverParty=&receiverService=&interface=SI_Co" +
            "nsultaRo_out&interfaceNamespace=http%3A%2F%2Fgeson.gob.mx%2FTRM%2FPORTAL%2FPagoE" +
            "nLinea")]
        public string Negocio_constancia_nuevo_validador_prod_SI_ConsultaRo_outService {
            get {
                return ((string)(this["Negocio_constancia_nuevo_validador_prod_SI_ConsultaRo_outService"]));
            }
        }
    }
}
