//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Negocio.WsPaseCaja_Calidad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_PaseCaja_outBinding", Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class SI_PaseCaja_outService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_PaseCaja_outOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_PaseCaja_outService() {
            this.Url = global::Negocio.Properties.Settings.Default.Negocio_WsPaseCaja_Calidad_SI_PaseCaja_outService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_PaseCaja_outCompletedEventHandler SI_PaseCaja_outCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_PaseCaja_resp", Namespace="http://geson.gob.mx/TRM/PORTAL/PaseAcaja")]
        public DT_RespuestaPaseCaja SI_PaseCaja_out([System.Xml.Serialization.XmlElementAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PaseAcaja")] DT_EntradaPaseCaja MT_PaseCaja_req) {
            object[] results = this.Invoke("SI_PaseCaja_out", new object[] {
                        MT_PaseCaja_req});
            return ((DT_RespuestaPaseCaja)(results[0]));
        }
        
        /// <remarks/>
        public void SI_PaseCaja_outAsync(DT_EntradaPaseCaja MT_PaseCaja_req) {
            this.SI_PaseCaja_outAsync(MT_PaseCaja_req, null);
        }
        
        /// <remarks/>
        public void SI_PaseCaja_outAsync(DT_EntradaPaseCaja MT_PaseCaja_req, object userState) {
            if ((this.SI_PaseCaja_outOperationCompleted == null)) {
                this.SI_PaseCaja_outOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_PaseCaja_outOperationCompleted);
            }
            this.InvokeAsync("SI_PaseCaja_out", new object[] {
                        MT_PaseCaja_req}, this.SI_PaseCaja_outOperationCompleted, userState);
        }
        
        private void OnSI_PaseCaja_outOperationCompleted(object arg) {
            if ((this.SI_PaseCaja_outCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_PaseCaja_outCompleted(this, new SI_PaseCaja_outCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_EntradaPaseCaja {
        
        private DT_Cabecera cabeceraField;
        
        private DT_Generales generalesField;
        
        private DT_ReferenciasISRTP[] iSRTPField;
        
        private DT_DatosDeclaracion[] declaracionField;
        
        private DT_PartidasAbiertas[] vehicularField;
        
        private DT_TablaVehiculosISAN[] iSANField;
        
        private DT_VigenciaLicencia vIgenciaLicenciaField;
        
        private DT_ApoyoSocial[] apoyoSocialField;
        
        private DT_Rubros[] rubrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Cabecera Cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Generales Generales {
            get {
                return this.generalesField;
            }
            set {
                this.generalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ReferenciasISRTP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_ReferenciasISRTP[] ISRTP {
            get {
                return this.iSRTPField;
            }
            set {
                this.iSRTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DatosDeclaracion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_DatosDeclaracion[] Declaracion {
            get {
                return this.declaracionField;
            }
            set {
                this.declaracionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PartidasAbiertas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_PartidasAbiertas[] Vehicular {
            get {
                return this.vehicularField;
            }
            set {
                this.vehicularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TablaVehiculosISAN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_TablaVehiculosISAN[] ISAN {
            get {
                return this.iSANField;
            }
            set {
                this.iSANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_VigenciaLicencia VIgenciaLicencia {
            get {
                return this.vIgenciaLicenciaField;
            }
            set {
                this.vIgenciaLicenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApoyoSocial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ApoyoSocial[] ApoyoSocial {
            get {
                return this.apoyoSocialField;
            }
            set {
                this.apoyoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rubros", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Rubros[] Rubros {
            get {
                return this.rubrosField;
            }
            set {
                this.rubrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_Cabecera {
        
        private string cOD_BPField;
        
        private string rFCField;
        
        private string tP_CTA_CONTRATOField;
        
        private string cOD_CTA_CONTRADOField;
        
        private string cLASE_OBJETOField;
        
        private string cOD_OBJ_CONTRATOField;
        
        private string cLAVE_PERIODOField;
        
        private System.DateTime fECHA_VENCIMIENTOField;
        
        private string nOMBRE_OPCIONAL_PCField;
        
        private string dIRECCION_OPCIONAL_PCField;
        
        private string cORREO_ELECTRONICOField;
        
        private string oBSERVACIONESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_BP {
            get {
                return this.cOD_BPField;
            }
            set {
                this.cOD_BPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TP_CTA_CONTRATO {
            get {
                return this.tP_CTA_CONTRATOField;
            }
            set {
                this.tP_CTA_CONTRATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_CTA_CONTRADO {
            get {
                return this.cOD_CTA_CONTRADOField;
            }
            set {
                this.cOD_CTA_CONTRADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLASE_OBJETO {
            get {
                return this.cLASE_OBJETOField;
            }
            set {
                this.cLASE_OBJETOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OBJ_CONTRATO {
            get {
                return this.cOD_OBJ_CONTRATOField;
            }
            set {
                this.cOD_OBJ_CONTRATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLAVE_PERIODO {
            get {
                return this.cLAVE_PERIODOField;
            }
            set {
                this.cLAVE_PERIODOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime FECHA_VENCIMIENTO {
            get {
                return this.fECHA_VENCIMIENTOField;
            }
            set {
                this.fECHA_VENCIMIENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRE_OPCIONAL_PC {
            get {
                return this.nOMBRE_OPCIONAL_PCField;
            }
            set {
                this.nOMBRE_OPCIONAL_PCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIRECCION_OPCIONAL_PC {
            get {
                return this.dIRECCION_OPCIONAL_PCField;
            }
            set {
                this.dIRECCION_OPCIONAL_PCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORREO_ELECTRONICO {
            get {
                return this.cORREO_ELECTRONICOField;
            }
            set {
                this.cORREO_ELECTRONICOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBSERVACIONES {
            get {
                return this.oBSERVACIONESField;
            }
            set {
                this.oBSERVACIONESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_Mensajes {
        
        private string tP_MENSField;
        
        private string iD_MENSField;
        
        private string v1_MENSField;
        
        private string v2_MENSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TP_MENS {
            get {
                return this.tP_MENSField;
            }
            set {
                this.tP_MENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string ID_MENS {
            get {
                return this.iD_MENSField;
            }
            set {
                this.iD_MENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V1_MENS {
            get {
                return this.v1_MENSField;
            }
            set {
                this.v1_MENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V2_MENS {
            get {
                return this.v2_MENSField;
            }
            set {
                this.v2_MENSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_ConveniosBancos {
        
        private string iD_BANCOField;
        
        private string cONVENIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID_BANCO {
            get {
                return this.iD_BANCOField;
            }
            set {
                this.iD_BANCOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONVENIO {
            get {
                return this.cONVENIOField;
            }
            set {
                this.cONVENIOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_ItemsPaseCaja {
        
        private string nRO_POSICIONField;
        
        private string aNIOField;
        
        private string pERIODOField;
        
        private string cONCEPTOField;
        
        private string dESCRIPCIONField;
        
        private string bASEField;
        
        private string cANTIDADField;
        
        private decimal iMPORTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NRO_POSICION {
            get {
                return this.nRO_POSICIONField;
            }
            set {
                this.nRO_POSICIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANIO {
            get {
                return this.aNIOField;
            }
            set {
                this.aNIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODO {
            get {
                return this.pERIODOField;
            }
            set {
                this.pERIODOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONCEPTO {
            get {
                return this.cONCEPTOField;
            }
            set {
                this.cONCEPTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASE {
            get {
                return this.bASEField;
            }
            set {
                this.bASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_PaseCaja {
        
        private string sEGURIDADField;
        
        private string fOLIOField;
        
        private string fECHAField;
        
        private string fEC_VENCIMIENTOField;
        
        private string rFCField;
        
        private string nOMBREField;
        
        private string dIRECCIONField;
        
        private decimal tOTALField;
        
        private string iMPORTE_LETRAField;
        
        private string lINEA_CAPTURAField;
        
        private string nOTAField;
        
        private string lEYENDAField;
        
        private string dATOS_PADRONField;
        
        private string lINEA_CAPOXXOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEGURIDAD {
            get {
                return this.sEGURIDADField;
            }
            set {
                this.sEGURIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FOLIO {
            get {
                return this.fOLIOField;
            }
            set {
                this.fOLIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FEC_VENCIMIENTO {
            get {
                return this.fEC_VENCIMIENTOField;
            }
            set {
                this.fEC_VENCIMIENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMPORTE_LETRA {
            get {
                return this.iMPORTE_LETRAField;
            }
            set {
                this.iMPORTE_LETRAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINEA_CAPTURA {
            get {
                return this.lINEA_CAPTURAField;
            }
            set {
                this.lINEA_CAPTURAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTA {
            get {
                return this.nOTAField;
            }
            set {
                this.nOTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LEYENDA {
            get {
                return this.lEYENDAField;
            }
            set {
                this.lEYENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATOS_PADRON {
            get {
                return this.dATOS_PADRONField;
            }
            set {
                this.dATOS_PADRONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINEA_CAPOXXO {
            get {
                return this.lINEA_CAPOXXOField;
            }
            set {
                this.lINEA_CAPOXXOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_RespuestaPaseCaja {
        
        private DT_PaseCaja pASE_CAJAField;
        
        private DT_ItemsPaseCaja[] iTEMS_PASE_CAJAField;
        
        private DT_ConveniosBancos[] cONVENIOS_BANCOSField;
        
        private DT_Mensajes[] mensajesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_PaseCaja PASE_CAJA {
            get {
                return this.pASE_CAJAField;
            }
            set {
                this.pASE_CAJAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMS_PASE_CAJA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ItemsPaseCaja[] ITEMS_PASE_CAJA {
            get {
                return this.iTEMS_PASE_CAJAField;
            }
            set {
                this.iTEMS_PASE_CAJAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONVENIOS_BANCOS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ConveniosBancos[] CONVENIOS_BANCOS {
            get {
                return this.cONVENIOS_BANCOSField;
            }
            set {
                this.cONVENIOS_BANCOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mensajes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Mensajes[] Mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PeriodoDeclararISRTP")]
    public partial class DT_Rubros {
        
        private string rEFERENCIAField;
        
        private string pERIODOField;
        
        private string tIPO_DECLField;
        
        private string fBNUMField;
        
        private string iD_ESTIMULOField;
        
        private string pORCENTAJEField;
        
        private string mONTOField;
        
        private string pAGADOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REFERENCIA {
            get {
                return this.rEFERENCIAField;
            }
            set {
                this.rEFERENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODO {
            get {
                return this.pERIODOField;
            }
            set {
                this.pERIODOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPO_DECL {
            get {
                return this.tIPO_DECLField;
            }
            set {
                this.tIPO_DECLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FBNUM {
            get {
                return this.fBNUMField;
            }
            set {
                this.fBNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID_ESTIMULO {
            get {
                return this.iD_ESTIMULOField;
            }
            set {
                this.iD_ESTIMULOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PORCENTAJE {
            get {
                return this.pORCENTAJEField;
            }
            set {
                this.pORCENTAJEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MONTO {
            get {
                return this.mONTOField;
            }
            set {
                this.mONTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAGADO {
            get {
                return this.pAGADOField;
            }
            set {
                this.pAGADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PeriodoDeclararISRTP")]
    public partial class DT_ApoyoSocial {
        
        private string idField;
        
        private string dESCRIPCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_VigenciaLicencia {
        
        private string vIG_LICENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VIG_LICEN {
            get {
                return this.vIG_LICENField;
            }
            set {
                this.vIG_LICENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_TablaVehiculosISAN {
        
        private string tIPOField;
        
        private string mODELOField;
        
        private string uNIDADESField;
        
        private decimal vALOR_ENAJENACIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MODELO {
            get {
                return this.mODELOField;
            }
            set {
                this.mODELOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string UNIDADES {
            get {
                return this.uNIDADESField;
            }
            set {
                this.uNIDADESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VALOR_ENAJENACION {
            get {
                return this.vALOR_ENAJENACIONField;
            }
            set {
                this.vALOR_ENAJENACIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_PartidasAbiertas {
        
        private string cOD_CONCEPTPField;
        
        private string cOD_OP_PRINCField;
        
        private string cOD_OP_PARCIField;
        
        private string dENOMINACIONField;
        
        private string pERIODOField;
        
        private decimal iMPORTEField;
        
        private string iND_BORRADOField;
        
        private string dOC_CONTABLEField;
        
        private string dOC_POS_1Field;
        
        private string dOC_POS_2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_CONCEPTP {
            get {
                return this.cOD_CONCEPTPField;
            }
            set {
                this.cOD_CONCEPTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OP_PRINC {
            get {
                return this.cOD_OP_PRINCField;
            }
            set {
                this.cOD_OP_PRINCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OP_PARCI {
            get {
                return this.cOD_OP_PARCIField;
            }
            set {
                this.cOD_OP_PARCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DENOMINACION {
            get {
                return this.dENOMINACIONField;
            }
            set {
                this.dENOMINACIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODO {
            get {
                return this.pERIODOField;
            }
            set {
                this.pERIODOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IND_BORRADO {
            get {
                return this.iND_BORRADOField;
            }
            set {
                this.iND_BORRADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_CONTABLE {
            get {
                return this.dOC_CONTABLEField;
            }
            set {
                this.dOC_CONTABLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_POS_1 {
            get {
                return this.dOC_POS_1Field;
            }
            set {
                this.dOC_POS_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_POS_2 {
            get {
                return this.dOC_POS_2Field;
            }
            set {
                this.dOC_POS_2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_DatosDeclaracion {
        
        private string nOM_CAMPOField;
        
        private string dES_CAMPOField;
        
        private string vAL_CAMPOField;
        
        private string iND_APLICField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOM_CAMPO {
            get {
                return this.nOM_CAMPOField;
            }
            set {
                this.nOM_CAMPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DES_CAMPO {
            get {
                return this.dES_CAMPOField;
            }
            set {
                this.dES_CAMPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VAL_CAMPO {
            get {
                return this.vAL_CAMPOField;
            }
            set {
                this.vAL_CAMPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IND_APLIC {
            get {
                return this.iND_APLICField;
            }
            set {
                this.iND_APLICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_ReferenciasISRTP {
        
        private string cOD_CTA_CONTRATOField;
        
        private string nOM_ORGANIZACIONField;
        
        private int nRO_MESField;
        
        private int nRO_EMPLEADOSField;
        
        private decimal bAS_GRAVABLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_CTA_CONTRATO {
            get {
                return this.cOD_CTA_CONTRATOField;
            }
            set {
                this.cOD_CTA_CONTRATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOM_ORGANIZACION {
            get {
                return this.nOM_ORGANIZACIONField;
            }
            set {
                this.nOM_ORGANIZACIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NRO_MES {
            get {
                return this.nRO_MESField;
            }
            set {
                this.nRO_MESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NRO_EMPLEADOS {
            get {
                return this.nRO_EMPLEADOSField;
            }
            set {
                this.nRO_EMPLEADOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BAS_GRAVABLE {
            get {
                return this.bAS_GRAVABLEField;
            }
            set {
                this.bAS_GRAVABLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_ZdettConceptos {
        
        private string cOD_CONCEPTPField;
        
        private string cOD_OP_PRINCField;
        
        private string cOD_OP_PARCIField;
        
        private decimal iMPORTEField;
        
        private int cANTIDADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_CONCEPTP {
            get {
                return this.cOD_CONCEPTPField;
            }
            set {
                this.cOD_CONCEPTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OP_PRINC {
            get {
                return this.cOD_OP_PRINCField;
            }
            set {
                this.cOD_OP_PRINCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OP_PARCI {
            get {
                return this.cOD_OP_PARCIField;
            }
            set {
                this.cOD_OP_PARCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_Domicilio {
        
        private string cALLEField;
        
        private string eNTRE_CALLESField;
        
        private string nRO_EXTField;
        
        private string nRO_INTField;
        
        private string mUNICIPIOField;
        
        private string lOCALIDADField;
        
        private string cOLONIAField;
        
        private string cOD_POSTALField;
        
        private string zONAField;
        
        private string eSTADOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CALLE {
            get {
                return this.cALLEField;
            }
            set {
                this.cALLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTRE_CALLES {
            get {
                return this.eNTRE_CALLESField;
            }
            set {
                this.eNTRE_CALLESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NRO_EXT {
            get {
                return this.nRO_EXTField;
            }
            set {
                this.nRO_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NRO_INT {
            get {
                return this.nRO_INTField;
            }
            set {
                this.nRO_INTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MUNICIPIO {
            get {
                return this.mUNICIPIOField;
            }
            set {
                this.mUNICIPIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOCALIDAD {
            get {
                return this.lOCALIDADField;
            }
            set {
                this.lOCALIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COLONIA {
            get {
                return this.cOLONIAField;
            }
            set {
                this.cOLONIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_POSTAL {
            get {
                return this.cOD_POSTALField;
            }
            set {
                this.cOD_POSTALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZONA {
            get {
                return this.zONAField;
            }
            set {
                this.zONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PaseAcaja")]
    public partial class DT_Generales {
        
        private DT_Domicilio domicilioField;
        
        private DT_ZdettConceptos[] conceptosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Domicilio Domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conceptos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ZdettConceptos[] Conceptos {
            get {
                return this.conceptosField;
            }
            set {
                this.conceptosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SI_PaseCaja_outCompletedEventHandler(object sender, SI_PaseCaja_outCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_PaseCaja_outCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_PaseCaja_outCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_RespuestaPaseCaja Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_RespuestaPaseCaja)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591