//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BovedaFielEntidades : DbContext
    {
        public BovedaFielEntidades()
            : base("name=BovedaFielEntidades")
        {
    		this.Configuration.ValidateOnSaveEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cadena> cadenas { get; set; }
        public virtual DbSet<operacion> operaciones { get; set; }
        public virtual DbSet<timestamping> timestampings { get; set; }
        public virtual DbSet<token> tokens { get; set; }
        public virtual DbSet<WSLoginCall> WSLoginCalls { get; set; }
        public virtual DbSet<xml> xmls { get; set; }
        public virtual DbSet<decodificacion> decodificaciones { get; set; }
    }
}
