//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class decodificacion
    {
        public long id { get; set; }
        public long idCadena { get; set; }
        public byte[] firma { get; set; }
        public byte[] certificado { get; set; }
        public string serie { get; set; }
        public string campos { get; set; }
        public long idOperacion { get; set; }
    
        public virtual cadena cadenas { get; set; }
        public virtual operacion operaciones { get; set; }
    }
}
