//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Firmas = new HashSet<Firma>();
            this.Carta = new HashSet<Carta>();
        }
    
        public int IDEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Celular { get; set; }
        public byte Sexo { get; set; }
        public string Rfc { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int IDPuesto { get; set; }
        public string UrlFoto { get; set; }
        public bool Habilitado { get; set; }
        public int IDTitulo { get; set; }
        public string UrlFirma { get; set; }
        public bool DefaultFirma { get; set; }
    
        public virtual Puesto Puesto { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firma> Firmas { get; set; }
        public virtual Titulo Titulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carta> Carta { get; set; }
    }
}
