//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sancion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sancion()
        {
            this.Carta = new HashSet<Carta>();
        }
    
        public int IDSancion { get; set; }
        public int TipoSancion { get; set; }
        public string NumeroExpediente { get; set; }
        public System.DateTime FechaEjecutoria { get; set; }
        public System.DateTime FechaResolucion { get; set; }
        public Nullable<int> Tipo { get; set; }
        public decimal Monto { get; set; }
        public int Año { get; set; }
        public int TiempoAños { get; set; }
        public int TiempoMeses { get; set; }
        public int TiempoDias { get; set; }
        public int IDEntidad { get; set; }
        public string EspecificarOtro { get; set; }
        public string Observaciones { get; set; }
        public bool Habilitado { get; set; }
        public Nullable<System.DateTime> PeriodoInicial { get; set; }
        public Nullable<System.DateTime> PeriodoFinal { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carta> Carta { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
