//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudContrasena
    {
        public int IDSolicitudContrasena { get; set; }
        public int IDUsuario { get; set; }
        public string Codigo { get; set; }
        public bool Usado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public byte TipoUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
