//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Carta = new HashSet<Carta>();
        }
    
        public int IDSolicitud { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tipo { get; set; }
        public string FolioPago { get; set; }
        public int Identificacion { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string URLPapeleta { get; set; }
        public string URLIdentificacion { get; set; }
        public string Codigo { get; set; }
        public MediosSolicitud Medio { get; set; }
        public bool Cancelada { get; set; }
        public string MotivoCancelacion { get; set; }
        public string NumeroDeOficio { get; set; }
        public string FolioPaseCaja { get; set; }
        public Nullable<System.DateTime> FechaCancelada { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carta> Carta { get; set; }
    }
}
