//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class timestamping
    {
        public long id { get; set; }
        public byte[] timestamp { get; set; }
        public long idcadena { get; set; }
        public long idoperacion { get; set; }
    
        public virtual cadena cadena { get; set; }
    }
}
