//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.ComponentModel;

    public enum TiposSancion : int
    {
        Apercibimiento = 1,
        Amonestación = 3,
        Suspensión = 2,
        DestituciónDelPuesto = 5,
        SanciónEconómica = 6,
        [Description("Inhabilitación para desempeñar empleos, cargos o comisiones en el SP")]
        InhabilitaciónDesempeñar = 4,
        AmonestaciónPrivada = 8,
        AmonestaciónPública = 9,
        DejarSinEfecto = 7,
        [Description("Inhabilitación y para participar en adquisiciones, arrendamientos, servicios u OP")]
        InhabilitaciónParticipar = 10
    }
}
