//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Negocio.mx.gob.sonora.claro.gespipci {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_ConsultaRo_outBinding", Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class SI_ConsultaRo_outService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_ConsultaRo_outOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_ConsultaRo_outService() {
            this.Url = global::Negocio.Properties.Settings.Default.Negocio_mx_gob_sonora_claro_gespipci_SI_ConsultaRo_outService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_ConsultaRo_outCompletedEventHandler SI_ConsultaRo_outCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_Consulta_resp", Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
        public DT_Consulta_resp SI_ConsultaRo_out([System.Xml.Serialization.XmlElementAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")] DT_Consulta_req MT_Consulta_req) {
            object[] results = this.Invoke("SI_ConsultaRo_out", new object[] {
                        MT_Consulta_req});
            return ((DT_Consulta_resp)(results[0]));
        }
        
        /// <remarks/>
        public void SI_ConsultaRo_outAsync(DT_Consulta_req MT_Consulta_req) {
            this.SI_ConsultaRo_outAsync(MT_Consulta_req, null);
        }
        
        /// <remarks/>
        public void SI_ConsultaRo_outAsync(DT_Consulta_req MT_Consulta_req, object userState) {
            if ((this.SI_ConsultaRo_outOperationCompleted == null)) {
                this.SI_ConsultaRo_outOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_ConsultaRo_outOperationCompleted);
            }
            this.InvokeAsync("SI_ConsultaRo_out", new object[] {
                        MT_Consulta_req}, this.SI_ConsultaRo_outOperationCompleted, userState);
        }
        
        private void OnSI_ConsultaRo_outOperationCompleted(object arg) {
            if ((this.SI_ConsultaRo_outCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_ConsultaRo_outCompleted(this, new SI_ConsultaRo_outCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_Consulta_req {
        
        private string pASECField;
        
        private string rECIBOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASEC {
            get {
                return this.pASECField;
            }
            set {
                this.pASECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECIBO {
            get {
                return this.rECIBOField;
            }
            set {
                this.rECIBOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_DatosRO {
        
        private string rECIBOField;
        
        private string pASE_CAJAField;
        
        private string tIPOField;
        
        private string iMPORTEField;
        
        private string pARTNERField;
        
        private string f_CREACIONField;
        
        private string nOMBREField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECIBO {
            get {
                return this.rECIBOField;
            }
            set {
                this.rECIBOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASE_CAJA {
            get {
                return this.pASE_CAJAField;
            }
            set {
                this.pASE_CAJAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNER {
            get {
                return this.pARTNERField;
            }
            set {
                this.pARTNERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F_CREACION {
            get {
                return this.f_CREACIONField;
            }
            set {
                this.f_CREACIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_Consulta_resp {
        
        private string sTATUSField;
        
        private DT_DatosRO dATOSField;
        
        private string sTR_B64Field;
        
        private DT_Consulta_respT_DETALLE[] t_DETALLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_DatosRO DATOS {
            get {
                return this.dATOSField;
            }
            set {
                this.dATOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STR_B64 {
            get {
                return this.sTR_B64Field;
            }
            set {
                this.sTR_B64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_DETALLE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Consulta_respT_DETALLE[] T_DETALLE {
            get {
                return this.t_DETALLEField;
            }
            set {
                this.t_DETALLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_Consulta_respT_DETALLE {
        
        private string eJERCICIOField;
        
        private string pERIODOField;
        
        private string cONCEPTOField;
        
        private string dESCRIPCIONField;
        
        private string bASEField;
        
        private string cANTIDADField;
        
        private string tOTALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EJERCICIO {
            get {
                return this.eJERCICIOField;
            }
            set {
                this.eJERCICIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODO {
            get {
                return this.pERIODOField;
            }
            set {
                this.pERIODOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONCEPTO {
            get {
                return this.cONCEPTOField;
            }
            set {
                this.cONCEPTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASE {
            get {
                return this.bASEField;
            }
            set {
                this.bASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SI_ConsultaRo_outCompletedEventHandler(object sender, SI_ConsultaRo_outCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_ConsultaRo_outCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_ConsultaRo_outCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_Consulta_resp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_Consulta_resp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591