//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Negocio.WsPagoRegistroCivil_Calidad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_PagoRegistroCivil_outBinding", Namespace="http://geson.gob.mx/PORTAL/WS/PagoRegistroCivil")]
    public partial class SI_PagoRegistroCivil_outService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_PagoRegistroCivil_outOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_PagoRegistroCivil_outService() {
            this.Url = global::Negocio.Properties.Settings.Default.Negocio_WsPagoRegistroCivil_Calidad_SI_PagoRegistroCivil_outService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_PagoRegistroCivil_outCompletedEventHandler SI_PagoRegistroCivil_outCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_CtaContrato_resp", Namespace="http://geson.gob.mx/TRM/PORTAL/PagoRegistroCivil")]
        public DT_PagoRegistroCivil SI_PagoRegistroCivil_out([System.Xml.Serialization.XmlElementAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoRegistroCivil")] DT_EntradaCtaContrato MT_CtaContrato_req) {
            object[] results = this.Invoke("SI_PagoRegistroCivil_out", new object[] {
                        MT_CtaContrato_req});
            return ((DT_PagoRegistroCivil)(results[0]));
        }
        
        /// <remarks/>
        public void SI_PagoRegistroCivil_outAsync(DT_EntradaCtaContrato MT_CtaContrato_req) {
            this.SI_PagoRegistroCivil_outAsync(MT_CtaContrato_req, null);
        }
        
        /// <remarks/>
        public void SI_PagoRegistroCivil_outAsync(DT_EntradaCtaContrato MT_CtaContrato_req, object userState) {
            if ((this.SI_PagoRegistroCivil_outOperationCompleted == null)) {
                this.SI_PagoRegistroCivil_outOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_PagoRegistroCivil_outOperationCompleted);
            }
            this.InvokeAsync("SI_PagoRegistroCivil_out", new object[] {
                        MT_CtaContrato_req}, this.SI_PagoRegistroCivil_outOperationCompleted, userState);
        }
        
        private void OnSI_PagoRegistroCivil_outOperationCompleted(object arg) {
            if ((this.SI_PagoRegistroCivil_outCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_PagoRegistroCivil_outCompleted(this, new SI_PagoRegistroCivil_outCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PagoRegistroCivil")]
    public partial class DT_EntradaCtaContrato {
        
        private string tP_CTA_CONTRATOField;
        
        private string cOBROField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TP_CTA_CONTRATO {
            get {
                return this.tP_CTA_CONTRATOField;
            }
            set {
                this.tP_CTA_CONTRATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COBRO {
            get {
                return this.cOBROField;
            }
            set {
                this.cOBROField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PagoRegistroCivil")]
    public partial class DT_Mensajes {
        
        private string tP_MENSField;
        
        private string iD_MENSField;
        
        private string v1_MENSField;
        
        private string v2_MENSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TP_MENS {
            get {
                return this.tP_MENSField;
            }
            set {
                this.tP_MENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string ID_MENS {
            get {
                return this.iD_MENSField;
            }
            set {
                this.iD_MENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V1_MENS {
            get {
                return this.v1_MENSField;
            }
            set {
                this.v1_MENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V2_MENS {
            get {
                return this.v2_MENSField;
            }
            set {
                this.v2_MENSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PagoRegistroCivil")]
    public partial class DT_Conceptos {
        
        private string cOD_CONCEPTPField;
        
        private string cOD_OP_PRINCField;
        
        private string cOD_OP_PARCIField;
        
        private string dESCRIPCIONField;
        
        private decimal iMPORTEField;
        
        private int cANTIDADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_CONCEPTP {
            get {
                return this.cOD_CONCEPTPField;
            }
            set {
                this.cOD_CONCEPTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OP_PRINC {
            get {
                return this.cOD_OP_PRINCField;
            }
            set {
                this.cOD_OP_PRINCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OP_PARCI {
            get {
                return this.cOD_OP_PARCIField;
            }
            set {
                this.cOD_OP_PARCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/PORTAL/WS/PagoRegistroCivil")]
    public partial class DT_PagoRegistroCivil {
        
        private string cOD_BPField;
        
        private string cOD_CTA_CONTRATOField;
        
        private string cOD_OBJ_CONTRATOField;
        
        private DT_Conceptos[] conceptosField;
        
        private DT_Mensajes[] mensajesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_BP {
            get {
                return this.cOD_BPField;
            }
            set {
                this.cOD_BPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_CTA_CONTRATO {
            get {
                return this.cOD_CTA_CONTRATOField;
            }
            set {
                this.cOD_CTA_CONTRATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_OBJ_CONTRATO {
            get {
                return this.cOD_OBJ_CONTRATOField;
            }
            set {
                this.cOD_OBJ_CONTRATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conceptos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Conceptos[] Conceptos {
            get {
                return this.conceptosField;
            }
            set {
                this.conceptosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mensajes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_Mensajes[] Mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SI_PagoRegistroCivil_outCompletedEventHandler(object sender, SI_PagoRegistroCivil_outCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_PagoRegistroCivil_outCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_PagoRegistroCivil_outCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_PagoRegistroCivil Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_PagoRegistroCivil)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591