//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carta()
        {
            this.Firma = new HashSet<Firma>();
            this.Sanciones = new HashSet<Sancion>();
        }
    
        public int IDCarta { get; set; }
        public string NumeroExpediente { get; set; }
        public TiposCarta Tipo { get; set; }
        public int IDSolicitud { get; set; }
        public string Cadena { get; set; }
        public System.DateTime Fecha { get; set; }
        public EstadosCarta Estado { get; set; }
        public int IDPlantilla { get; set; }
        public Nullable<int> IDEmpleadoRechazo { get; set; }
        public Nullable<System.DateTime> FechaRechazo { get; set; }
        public bool Consultable { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Plantilla Plantilla { get; set; }
        public virtual Solicitud Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firma> Firma { get; set; }
        public virtual Precio Precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sancion> Sanciones { get; set; }
    }
}
