//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public int IDFirma { get; set; }
        public int IDCarta { get; set; }
        public int IDLote { get; set; }
        public FirmaEstados Estado { get; set; }
        public Nullable<long> BovedaFiel_IDCadena { get; set; }
        public Nullable<long> BovedaFiel_IDTimeStamping { get; set; }
        public string UbicacionXml { get; set; }
        public string Error { get; set; }
        public string Valor { get; set; }
        public int IDEmpleado { get; set; }
    
        public virtual Lote Lote { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Carta Carta { get; set; }
    }
}
