//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaseCaja
    {
        public int IDPaseCaja { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string NombrePersona { get; set; }
        public string CorreoElectronico { get; set; }
        public string UbicacionArchivo { get; set; }
        public bool EstaPagado { get; set; }
    }
}
