//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public token()
        {
            this.operaciones = new HashSet<operacion>();
        }
    
        public long id { get; set; }
        public string valorToken { get; set; }
        public long idwscall { get; set; }
        public System.DateTime validoDesde { get; set; }
        public System.DateTime validoHasta { get; set; }
        public string appid { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operacion> operaciones { get; set; }
        public virtual WSLoginCall WSLoginCall { get; set; }
    }
}
