//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.ConsultaPaseCajaQA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea", ConfigurationName="ConsultaPaseCajaQA.SI_ConsultaRo_out")]
    public interface SI_ConsultaRo_out {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SI_ConsultaRo_out no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outResponse SI_ConsultaRo_out(Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outResponse> SI_ConsultaRo_outAsync(Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_Consulta_req : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pASECField;
        
        private string rECIBOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PASEC {
            get {
                return this.pASECField;
            }
            set {
                this.pASECField = value;
                this.RaisePropertyChanged("PASEC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RECIBO {
            get {
                return this.rECIBOField;
            }
            set {
                this.rECIBOField = value;
                this.RaisePropertyChanged("RECIBO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_DatosRO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rECIBOField;
        
        private string pASE_CAJAField;
        
        private string tIPOField;
        
        private string iMPORTEField;
        
        private string pARTNERField;
        
        private string f_CREACIONField;
        
        private string nOMBREField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RECIBO {
            get {
                return this.rECIBOField;
            }
            set {
                this.rECIBOField = value;
                this.RaisePropertyChanged("RECIBO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PASE_CAJA {
            get {
                return this.pASE_CAJAField;
            }
            set {
                this.pASE_CAJAField = value;
                this.RaisePropertyChanged("PASE_CAJA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
                this.RaisePropertyChanged("IMPORTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PARTNER {
            get {
                return this.pARTNERField;
            }
            set {
                this.pARTNERField = value;
                this.RaisePropertyChanged("PARTNER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string F_CREACION {
            get {
                return this.f_CREACIONField;
            }
            set {
                this.f_CREACIONField = value;
                this.RaisePropertyChanged("F_CREACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_Consulta_resp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sTATUSField;
        
        private DT_DatosRO dATOSField;
        
        private string sTR_B64Field;
        
        private DT_Consulta_respT_DETALLE[] t_DETALLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_DatosRO DATOS {
            get {
                return this.dATOSField;
            }
            set {
                this.dATOSField = value;
                this.RaisePropertyChanged("DATOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string STR_B64 {
            get {
                return this.sTR_B64Field;
            }
            set {
                this.sTR_B64Field = value;
                this.RaisePropertyChanged("STR_B64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_DETALLE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DT_Consulta_respT_DETALLE[] T_DETALLE {
            get {
                return this.t_DETALLEField;
            }
            set {
                this.t_DETALLEField = value;
                this.RaisePropertyChanged("T_DETALLE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea")]
    public partial class DT_Consulta_respT_DETALLE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eJERCICIOField;
        
        private string pERIODOField;
        
        private string cONCEPTOField;
        
        private string dESCRIPCIONField;
        
        private string bASEField;
        
        private string cANTIDADField;
        
        private string tOTALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EJERCICIO {
            get {
                return this.eJERCICIOField;
            }
            set {
                this.eJERCICIOField = value;
                this.RaisePropertyChanged("EJERCICIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PERIODO {
            get {
                return this.pERIODOField;
            }
            set {
                this.pERIODOField = value;
                this.RaisePropertyChanged("PERIODO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONCEPTO {
            get {
                return this.cONCEPTOField;
            }
            set {
                this.cONCEPTOField = value;
                this.RaisePropertyChanged("CONCEPTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BASE {
            get {
                return this.bASEField;
            }
            set {
                this.bASEField = value;
                this.RaisePropertyChanged("BASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
                this.RaisePropertyChanged("TOTAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ConsultaRo_outRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea", Order=0)]
        public Negocio.ConsultaPaseCajaQA.DT_Consulta_req MT_Consulta_req;
        
        public SI_ConsultaRo_outRequest() {
        }
        
        public SI_ConsultaRo_outRequest(Negocio.ConsultaPaseCajaQA.DT_Consulta_req MT_Consulta_req) {
            this.MT_Consulta_req = MT_Consulta_req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ConsultaRo_outResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://geson.gob.mx/TRM/PORTAL/PagoEnLinea", Order=0)]
        public Negocio.ConsultaPaseCajaQA.DT_Consulta_resp MT_Consulta_resp;
        
        public SI_ConsultaRo_outResponse() {
        }
        
        public SI_ConsultaRo_outResponse(Negocio.ConsultaPaseCajaQA.DT_Consulta_resp MT_Consulta_resp) {
            this.MT_Consulta_resp = MT_Consulta_resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ConsultaRo_outChannel : Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ConsultaRo_outClient : System.ServiceModel.ClientBase<Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_out>, Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_out {
        
        public SI_ConsultaRo_outClient() {
        }
        
        public SI_ConsultaRo_outClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ConsultaRo_outClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ConsultaRo_outClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ConsultaRo_outClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outResponse Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_out.SI_ConsultaRo_out(Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest request) {
            return base.Channel.SI_ConsultaRo_out(request);
        }
        
        public Negocio.ConsultaPaseCajaQA.DT_Consulta_resp SI_ConsultaRo_out(Negocio.ConsultaPaseCajaQA.DT_Consulta_req MT_Consulta_req) {
            Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest inValue = new Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest();
            inValue.MT_Consulta_req = MT_Consulta_req;
            Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outResponse retVal = ((Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_out)(this)).SI_ConsultaRo_out(inValue);
            return retVal.MT_Consulta_resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outResponse> Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_out.SI_ConsultaRo_outAsync(Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest request) {
            return base.Channel.SI_ConsultaRo_outAsync(request);
        }
        
        public System.Threading.Tasks.Task<Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outResponse> SI_ConsultaRo_outAsync(Negocio.ConsultaPaseCajaQA.DT_Consulta_req MT_Consulta_req) {
            Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest inValue = new Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_outRequest();
            inValue.MT_Consulta_req = MT_Consulta_req;
            return ((Negocio.ConsultaPaseCajaQA.SI_ConsultaRo_out)(this)).SI_ConsultaRo_outAsync(inValue);
        }
    }
}
